// Objective-C API for talking to command-line-arguments Go package.
//   gobind -lang=objc command-line-arguments
//
// File is generated by gobind. Do not edit.

#ifndef __GO_panicker_H__
#define __GO_panicker_H__

#include <stdint.h>
#include <objc/objc.h>
typedef struct cproxypanicker_Panicker_Panic_return {
	nbyteslice r0;
	int32_t r1;
} cproxypanicker_Panicker_Panic_return;
struct cproxypanicker_Panicker_Panic_return cproxypanicker_Panicker_Panic(int32_t refnum, nbyteslice p0);

#endif
